### ISSUE TITLE
Error building  flightcrew  with clang

### ISSUE THREAD

**Issue by slacka** [Sigil-Ebook/flightcrew#49]
Building flightcrew with Clang results in:
`LocationAwareDOMParser.cpp:32:49: error: default initialization of an object of const type 'const XercesExt::LocationInfoDataHandler' without a user-provided default constructor`

Full log:
http://clang.debian.net/logs/2016-08-30/flightcrew_0.7.2+dfsg-7_unstable_clang.log

**Comment by kevinhendricks** [comment]
Closing as this repo is being archived.
