### ISSUE TITLE
On OS X the plugin remains grey when trying to add it in manage plugins

### ISSUE THREAD

**Issue by wrcstewart** [Sigil-Ebook/flightcrew#50]
I also tried clicking on the exec and setting security to open.
Is there some separate place to control security for application plugins??

**Comment by dougmassay** [comment]
You don't open or execute a plugin's zipfile. You add it to Sigil as is. Using Sigil's Manage Plugins->Add Plugin to select the zipfile. After that, Flightcrew will be available under the Plugins->Validation menu.

NOTE: you must not rename a plugin's zipfile. The naming of a Sigil plugin is crucial.

**Comment by wrcstewart** [comment]
Thank-you for the swift reply.
The first thing I tried was what you suggested - that seemed natural enough. But I cannot select the plugin because it remains greyed out in the file list.

**Comment by dougmassay** [comment]
Sounds to me like something is automatically unzipping the plugin after you download it. The file dialog for Add Plugin will only allow you to select *.zip files. If there's nothing available for you to select, then you don't have a zip file.

More than likely, you need to uncheck the option in Safari that is set to "Open 'safe' files after downloading.

**Comment by wrcstewart** [comment]
Thanks I'll try those options
