### ISSUE TITLE
src/FlightCrew/Misc/CustomAssert.cpp:100: use of out of scope variable

### ISSUE THREAD

**Issue by dcb314** [Sigil-Ebook/flightcrew#51]
FlightCrew-0.9.1/src/FlightCrew/Misc/CustomAssert.cpp:100]: (error) Using pointer to local variable 'messageBuffer' that is out of scope.

Source code is

        if (msg != NULL)
        {
                char messageBuffer[1024];
                {
                        va_list args;
                        va_start(args, msg);

            #if defined(_MSC_VER)
                        vsnprintf_s(messageBuffer, 1024, 1024, msg, args);
            #else
            vsnprintf(messageBuffer, 1024, msg, args);
            #endif

                        va_end(args);
                }

                message = messageBuffer;
        }

        return GetAssertHandlerInstance()(condition, message, file, line);

**Comment by kevinhendricks** [comment]
Closing as this repository is being archived.
