### ISSUE TITLE
Infinite Loop in Zipios

### ISSUE THREAD

**Issue by mssalvatore** [Sigil-Ebook/flightcrew#54]
FlightCrew can be sent into an infinite loop if provided with a malformed ZIP/EPUB file.

To reproduce, run `flightcrew-cli --input-file hang.zip` using the attached [hang.zip](https://github.com/Sigil-Ebook/flightcrew/files/3388092/hang.zip)

This issue occurs in the Zipios v1.5.9 library embedded in flightcrew. The Zipios project has released a patch that can be applied to flightcrew to resolve this issue. https://sourceforge.net/p/zipios/code-git/ci/96e26640573410709bb863b8916a8216f4c6a546/tree/infinite_loop.patch

**Comment by dougmassay** [comment]
Addressed with #55 , thanks.
