### ISSUE TITLE
Current official FlightCrew upstream?

### ISSUE THREAD

**Issue by mzf-guest** [Sigil-Ebook/flightcrew#56]
Hello,

I'm currently trying to maintain the [Debian's FlightCrew package](https://tracker.debian.org/pkg/flightcrew), especially fixing the CVE's.
The original code of FlightCrew at [google code](https://code.google.com/archive/p/flightcrew/) is not maintained anymore but your repo looks like the most up-to-date version of FlightCrew.

So, should we consider https://github.com/Sigil-Ebook/flightcrew/ as the current official FlightCrew code?

Thanks

**Comment by kevinhendricks** [comment]
Yes, it always has been.  We moved to github when google took away google code.
Previous to that flightcrew was integrated inside of Sigil.

All of the CVEs that have been reported to us are already fixed in master.

Kevin

**Comment by mzf-guest** [comment]
Great!

It would be great to use official tag when updating the Debian package. The current latest release of FlightCrew is 0.9.2 according to the [release's tags](https://github.com/Sigil-Ebook/flightcrew/releases). 

Could you please tag the master branch with more recent commits, including the CVE fixes (Sigil is currently 0.9.16)?

Thanks,

**Comment by kevinhendricks** [comment]
Just tagged master as 0.9.3

**Comment by mzf-guest** [comment]
Thanks!
