### ISSUE TITLE
Error Parsing Result XML: Premature end of document

### ISSUE THREAD

**Issue by kiwiG** [Sigil-Ebook/flightcrew#58]
Getting the above error running Flightcrew on Sigil 1.3.0 on Ubuntu Linux 18.04.5 LTS.

Click Details returns:
```
Traceback (most recent call last):
  File "/usr/local/share/sigil/plugin_launchers/python/launcher.py", line 51, in <module>
    from opf_parser import Opf_Parser
  File "/usr/local/share/sigil/plugin_launchers/python/opf_parser.py", line 32, in <module>

    from hrefutils import unquoteurl, buildBookPath, startingDir, longestCommonPath
  File "/usr/local/share/sigil/plugin_launchers/python/hrefutils.py", line 7, in <module>
    from urllib.parse import unquote
ImportError: No module named parse
```
Any clues?

**Comment by dougmassay** [comment]
That's a puzzler. Urllib.parse is a python 3 standard library. Did you build Sigil 1.3 against the standard Ubuntu 18.04 system python 3?

**Comment by kevinhendricks** [comment]
Python 2 has urllib but no urllib.parse.  Could you have built against python 2.7 somehow instead of python 3.5 or later?

**Comment by dougmassay** [comment]
You shouldn't be able to build Sigil against python 2 without a lot of finagling. But setting the path to the python2 binary in the plugin manager dialog might cause this.

**Comment by kevinhendricks** [comment]
Yes, that must be what is going on!  Easy fix ...   in the Plugin Manager 's Preferences Dialog, please make sure you have set a path to a Python 3.5 version and not a python 2.7 version.

**Comment by kevinhendricks** [comment]
Closing this as not an issue with flightcrew itself.  User has not configured the plugin engine in Sigil properly.
